apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: meridian-air
  namespace: flux-system
spec:
  image: ghcr.io/aisbilir/meridian-analytics
  interval: 1m
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: meridian-air
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: meridian-air
  filterTags:
    pattern: '^main-(?P<ts>\d+)-[a-f0-9]+$'
    extract: '$ts'
  policy:
    numerical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageUpdateAutomation
metadata:
  name: meridian
  namespace: flux-system
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        name: fluxcdbot
        email: fluxcdbot@users.noreply.github.com
      messageTemplate: 'chore(images): update image tags'
    push:
      branch: main
  update:
    path: ./k8s
    strategy: Setters