apiVersion: apps/v1
kind: Deployment
metadata:
  name: meridian-air
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meridian-air
  template:
    metadata:
      labels:
        app: meridian-air
    spec:
      containers:
      - name: meridian-air
        image: ghcr.io/aisbilir/meridian-analytics:main-20260907044004-e55bdf2 # {"$imagepolicy": "flux-system:meridian-air"}
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        envFrom:
        - secretRef:
            name: opensky-credentials
        - secretRef:
            name: postgres-credentials